// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__JSON from "@rescript/core/src/Core__JSON.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

function toApi(message) {
  return {
          role: message.role,
          content: message.content
        };
}

function decodeRole(json) {
  var match = Core__JSON.Decode.string(json);
  if (match === undefined) {
    return ;
  }
  switch (match) {
    case "assistant" :
        return "assistant";
    case "system" :
        return "system";
    case "user" :
        return "user";
    default:
      return ;
  }
}

function decode(json) {
  var dict = Core__JSON.Decode.object(json);
  if (dict === undefined) {
    return ;
  }
  var match = dict["role"];
  var match$1 = dict["content"];
  if (match === undefined) {
    return ;
  }
  if (match$1 === undefined) {
    return ;
  }
  var match$2 = decodeRole(match);
  var match$3 = Core__JSON.Decode.string(match$1);
  if (match$2 !== undefined && match$3 !== undefined) {
    return {
            role: match$2,
            content: match$3
          };
  }
  
}

function decodeRequest(json) {
  var dict = Core__JSON.Decode.object(json);
  if (dict === undefined) {
    return {
            TAG: "Error",
            _0: "Expected a JSON object with a messages array"
          };
  }
  var messagesJson = dict["messages"];
  if (messagesJson === undefined) {
    return {
            TAG: "Error",
            _0: "Missing messages"
          };
  }
  var items = Core__JSON.Decode.array(messagesJson);
  if (items === undefined) {
    return {
            TAG: "Error",
            _0: "messages must be an array"
          };
  }
  var count = items.length;
  if (count === 0) {
    return {
            TAG: "Error",
            _0: "messages must not be empty"
          };
  } else if (count > 50) {
    return {
            TAG: "Error",
            _0: "Too many messages (max 50)"
          };
  } else {
    return Core__Array.reduce(items, {
                TAG: "Ok",
                _0: []
              }, (function (acc, item) {
                  if (acc.TAG !== "Ok") {
                    return {
                            TAG: "Error",
                            _0: acc._0
                          };
                  }
                  var message = decode(item);
                  if (message !== undefined) {
                    if (message.content.length > 32000) {
                      return {
                              TAG: "Error",
                              _0: "Message content is too long"
                            };
                    } else {
                      return {
                              TAG: "Ok",
                              _0: acc._0.concat([message])
                            };
                    }
                  } else {
                    return {
                            TAG: "Error",
                            _0: "Each message needs a role and content string"
                          };
                  }
                }));
  }
}

function errorMessage(json) {
  var root = Core__JSON.Decode.object(json);
  if (root === undefined) {
    return Core__JSON.Decode.string(json);
  }
  var errorJson = root["error"];
  if (errorJson !== undefined) {
    var errorDict = Core__JSON.Decode.object(errorJson);
    if (errorDict === undefined) {
      return Core__JSON.Decode.string(errorJson);
    }
    var messageJson = errorDict["message"];
    if (messageJson !== undefined) {
      return Core__JSON.Decode.string(messageJson);
    } else {
      return ;
    }
  }
  var messageJson$1 = root["message"];
  if (messageJson$1 !== undefined) {
    return Core__JSON.Decode.string(messageJson$1);
  }
  
}

function deltaFromChunk(raw) {
  try {
    var json = JSON.parse(raw);
    var root = Core__JSON.Decode.object(json);
    if (root === undefined) {
      return ;
    }
    var choicesJson = root["choices"];
    if (choicesJson === undefined) {
      return ;
    }
    var choices = Core__JSON.Decode.array(choicesJson);
    if (choices === undefined) {
      return ;
    }
    var choiceJson = choices[0];
    if (choiceJson === undefined) {
      return ;
    }
    var choice = Core__JSON.Decode.object(choiceJson);
    if (choice === undefined) {
      return ;
    }
    var deltaJson = choice["delta"];
    if (deltaJson === undefined) {
      return ;
    }
    var delta = Core__JSON.Decode.object(deltaJson);
    if (delta === undefined) {
      return ;
    }
    var contentJson = delta["content"];
    if (contentJson !== undefined) {
      return Core__JSON.Decode.string(contentJson);
    } else {
      return ;
    }
  }
  catch (exn){
    return ;
  }
}

export {
  toApi ,
  decodeRole ,
  decode ,
  decodeRequest ,
  errorMessage ,
  deltaFromChunk ,
}
/* No side effect */
