// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WebApi from "../bindings/WebApi.res.mjs";
import * as Message from "./Message.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var Env = {};

function nonEmpty(value) {
  if (value == null) {
    return ;
  }
  var trimmed = value.trim();
  if (trimmed === "") {
    return ;
  } else {
    return trimmed;
  }
}

var defaultBaseUrl = "https://api.openai.com/v1";

var defaultModel = "gpt-4o-mini";

function baseUrl() {
  return Core__Option.getOr(nonEmpty(process.env.OPENAI_BASE_URL), defaultBaseUrl);
}

function model() {
  return Core__Option.getOr(nonEmpty(process.env.OPENAI_MODEL), defaultModel);
}

function apiKey() {
  return nonEmpty(process.env.OPENAI_API_KEY);
}

function systemPrompt() {
  return nonEmpty(process.env.OPENAI_SYSTEM_PROMPT);
}

function trimSlash(url) {
  if (url.endsWith("/")) {
    return url.slice(0, url.length - 1 | 0);
  } else {
    return url;
  }
}

function isDemo() {
  var match = nonEmpty(process.env.OPENAI_API_KEY);
  var match$1 = nonEmpty(process.env.OPENAI_BASE_URL);
  if (match !== undefined) {
    return false;
  } else {
    return match$1 === undefined;
  }
}

function publicConfig() {
  return {
          demo: isDemo(),
          model: isDemo() ? "demo" : model()
        };
}

var demoText = "This is demo mode. Tokens are streamed locally because OPENAI_API_KEY is not set.\n\nAdd a .env.local file:\n\nOPENAI_API_KEY=sk-...\nOPENAI_BASE_URL=https://api.openai.com/v1\nOPENAI_MODEL=gpt-4o-mini\n\nOPENAI_BASE_URL can point at any OpenAI-compatible provider — OpenRouter, Groq, Ollama, Azure, vLLM, and others.";

function encodeSseChunk(content) {
  var payload = {
    choices: [{
        delta: {
          content: content
        }
      }]
  };
  return "data: " + Core__Option.getOr(JSON.stringify(payload), "{}") + "\n\n";
}

function makeDemoStream() {
  var encoder = new TextEncoder();
  var words = demoText.split(" ");
  var index = {
    contents: 0
  };
  return new ReadableStream({
              start: (function (controller) {
                  var sendNext = async function () {
                    if (index.contents >= words.length) {
                      controller.enqueue(encoder.encode("data: [DONE]\n\n"));
                      controller.close();
                      return ;
                    }
                    var word = Core__Option.getOr(words[index.contents], "");
                    var suffix = index.contents < (words.length - 1 | 0) ? " " : "";
                    controller.enqueue(encoder.encode(encodeSseChunk(word + suffix)));
                    index.contents = index.contents + 1 | 0;
                    await WebApi.wait(22);
                    return await sendNext();
                  };
                  sendNext();
                })
            });
}

function withSystemPrompt(messages) {
  var content = nonEmpty(process.env.OPENAI_SYSTEM_PROMPT);
  if (content === undefined) {
    return messages;
  }
  var systemMessage = {
    role: "system",
    content: content
  };
  return [systemMessage].concat(messages);
}

async function complete(messages) {
  if (isDemo()) {
    return {
            TAG: "Ok",
            _0: makeDemoStream()
          };
  }
  var url = trimSlash(baseUrl()) + "/chat/completions";
  var headers = Object.fromEntries([[
          "Content-Type",
          "application/json"
        ]]);
  var key = nonEmpty(process.env.OPENAI_API_KEY);
  if (key !== undefined) {
    headers["Authorization"] = "Bearer " + key;
  }
  var body = {
    model: model(),
    stream: true,
    messages: withSystemPrompt(messages)
  };
  try {
    var response = await fetch(url, {
          method: "POST",
          headers: headers,
          body: Core__Option.getOr(JSON.stringify(body), "{}")
        });
    if (response.ok) {
      var stream = response.body;
      if (stream == null) {
        return {
                TAG: "Error",
                _0: {
                  status: 502,
                  message: "Upstream response had no body"
                }
              };
      } else {
        return {
                TAG: "Ok",
                _0: stream
              };
      }
    }
    var payload;
    try {
      payload = await response.json();
    }
    catch (exn){
      payload = await response.text();
    }
    return {
            TAG: "Error",
            _0: {
              status: response.status,
              message: Core__Option.getOr(Message.errorMessage(payload), "Upstream request failed")
            }
          };
  }
  catch (raw_exn){
    var exn$1 = Caml_js_exceptions.internalToOCamlException(raw_exn);
    var err = Caml_js_exceptions.as_js_exn(exn$1);
    return {
            TAG: "Error",
            _0: {
              status: 502,
              message: err !== undefined ? Core__Option.getOr(Caml_option.valFromOption(err).message, "Failed to reach the model provider") : "Failed to reach the model provider"
            }
          };
  }
}

var streamHeaders = Object.fromEntries([
      [
        "Content-Type",
        "text/event-stream; charset=utf-8"
      ],
      [
        "Cache-Control",
        "no-cache, no-transform"
      ],
      [
        "Connection",
        "keep-alive"
      ],
      [
        "X-Accel-Buffering",
        "no"
      ]
    ]);

export {
  Env ,
  nonEmpty ,
  defaultBaseUrl ,
  defaultModel ,
  baseUrl ,
  model ,
  apiKey ,
  systemPrompt ,
  trimSlash ,
  isDemo ,
  publicConfig ,
  demoText ,
  encodeSseChunk ,
  makeDemoStream ,
  withSystemPrompt ,
  complete ,
  streamHeaders ,
}
/* streamHeaders Not a pure module */
