// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Message from "./Message.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function splitLines(buffer) {
  var parts = buffer.split("\n");
  var lastIndex = parts.length - 1 | 0;
  var rest = Core__Option.getOr(parts[lastIndex], "");
  var complete = parts.slice(0, lastIndex);
  return [
          rest,
          complete
        ];
}

function parseLine(line) {
  var trimmed = line.trim();
  if (trimmed === "" || trimmed.startsWith(":")) {
    return "Ignore";
  }
  if (!trimmed.startsWith("data:")) {
    return "Ignore";
  }
  var data = trimmed.slice(5).trim();
  if (data === "[DONE]") {
    return "Done";
  }
  var text = Message.deltaFromChunk(data);
  if (text !== undefined && text !== "") {
    return {
            TAG: "Delta",
            _0: text
          };
  } else {
    return "Ignore";
  }
}

function consume(stream, onDelta) {
  var reader = stream.getReader();
  var decoder = new TextDecoder();
  var loop = function (buffer) {
    return reader.read().then(function (result) {
                if (result.done) {
                  return Promise.resolve();
                }
                var bytes = result.value;
                var next = (bytes == null) ? buffer : buffer + decoder.decode(bytes);
                var match = splitLines(next);
                var lines = match[1];
                var walk = function (_index, _finished) {
                  while(true) {
                    var finished = _finished;
                    var index = _index;
                    if (finished || index >= lines.length) {
                      return finished;
                    }
                    var text = parseLine(Core__Option.getOr(lines[index], ""));
                    if (typeof text !== "object") {
                      if (text === "Done") {
                        return true;
                      }
                      _finished = false;
                      _index = index + 1 | 0;
                      continue ;
                    } else {
                      onDelta(text._0);
                      _finished = false;
                      _index = index + 1 | 0;
                      continue ;
                    }
                  };
                };
                if (walk(0, false)) {
                  return Promise.resolve();
                } else {
                  return loop(match[0]);
                }
              });
  };
  return loop("");
}

export {
  splitLines ,
  parseLine ,
  consume ,
}
/* No side effect */
