// Generated by ReScript, PLEASE EDIT WITH CARE


var Iterator = {};

var $$Response = {};

var ServerComponent = {};

function get(prim0, prim1) {
  return prim0.get(prim1);
}

function getAll(prim0, prim1) {
  return prim0.getAll(prim1);
}

function has(prim0, prim1) {
  return prim0.has(prim1);
}

function entries(prim) {
  return prim.entries();
}

var ServerActions = {
  get: get,
  getAll: getAll,
  has: has,
  entries: entries
};

var $$Response$1 = {};

var RouteHandler = {
  $$Response: $$Response$1
};

var Cookies = {};

var $$Headers = {};

var Params = {};

var Revalidation = {};

var Cache = {};

export {
  Iterator ,
  $$Response ,
  ServerComponent ,
  ServerActions ,
  RouteHandler ,
  Cookies ,
  $$Headers ,
  Params ,
  Revalidation ,
  Cache ,
}
/* No side effect */
