// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Navigation = {};

var Link = {};

var $$Image = {};

function make(title, description, keywords, openGraph, twitter, robots, param) {
  return {
          title: title,
          description: description,
          keywords: keywords,
          authors: undefined,
          creator: undefined,
          publisher: undefined,
          robots: robots,
          openGraph: openGraph,
          twitter: twitter,
          manifest: undefined,
          icons: undefined
        };
}

var Metadata = {
  make: make
};

var ErrorHandling = {};

var Loading = {};

export {
  $$Navigation ,
  Link ,
  $$Image ,
  Metadata ,
  ErrorHandling ,
  Loading ,
}
/* No side effect */
