// Generated by ReScript, PLEASE EDIT WITH CARE


function wait(ms) {
  return new Promise((function (resolve, _reject) {
                setTimeout((function () {
                        resolve();
                      }), ms);
              }));
}

function scrollToBottom(el) {
  el.scrollIntoView({
        behavior: "smooth",
        block: "end"
      });
}

function isAbortError(err) {
  var match = err.name;
  if (match === "AbortError") {
    return true;
  } else {
    return false;
  }
}

export {
  wait ,
  scrollToBottom ,
  isAbortError ,
}
/* No side effect */
