'use client'
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sse from "../chat/Sse.res.mjs";
import * as React from "react";
import * as WebApi from "../bindings/WebApi.res.mjs";
import * as Message from "../chat/Message.res.mjs";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var prompts = [
  "What is an OpenAI-compatible API?",
  "Explain ReScript records vs objects.",
  "Write a Next.js App Router route handler."
];

function Chat(props) {
  var match = React.useState(function () {
        return [];
      });
  var setMessages = match[1];
  var messages = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setInput = match$1[1];
  var input = match$1[0];
  var match$2 = React.useState(function () {
        return "Idle";
      });
  var setStatus = match$2[1];
  var match$3 = React.useState(function () {
        
      });
  var setError = match$3[1];
  var error = match$3[0];
  var match$4 = React.useState(function () {
        
      });
  var setConfig = match$4[1];
  var config = match$4[0];
  var abortRef = React.useRef(undefined);
  var idRef = React.useRef(0);
  var bottomRef = React.useRef(null);
  var nextId = function () {
    idRef.current = idRef.current + 1 | 0;
    return idRef.current.toString();
  };
  var streaming = match$2[0] === "Streaming";
  React.useEffect((function () {
          var cancelled = {
            contents: false
          };
          var load = async function () {
            try {
              var response = await fetch("/api/chat", {
                    method: "GET"
                  });
              if (!response.ok) {
                return ;
              }
              var json = await response.json();
              var dict = Core__JSON.Decode.object(json);
              if (dict === undefined) {
                return ;
              }
              var value = dict["demo"];
              var demo = value !== undefined ? Core__Option.getOr(Core__JSON.Decode.bool(value), false) : false;
              var value$1 = dict["model"];
              var model = value$1 !== undefined ? Core__Option.getOr(Core__JSON.Decode.string(value$1), "unknown") : "unknown";
              if (!cancelled.contents) {
                return setConfig(function (param) {
                            return {
                                    demo: demo,
                                    model: model
                                  };
                          });
              } else {
                return ;
              }
            }
            catch (exn){
              return ;
            }
          };
          load();
          return (function () {
                    cancelled.contents = true;
                  });
        }), []);
  React.useEffect((function () {
          var el = bottomRef.current;
          if (!(el == null)) {
            WebApi.scrollToBottom(el);
          }
          
        }), [messages]);
  var stop = function () {
    var controller = abortRef.current;
    if (controller !== undefined) {
      Caml_option.valFromOption(controller).abort();
    }
    abortRef.current = undefined;
    setStatus(function (param) {
          return "Idle";
        });
  };
  var appendDelta = function (delta) {
    setMessages(function (prev) {
          var lastIndex = prev.length - 1 | 0;
          return prev.map(function (message, index) {
                      if (index === lastIndex && message.role === "assistant") {
                        return {
                                id: message.id,
                                role: message.role,
                                content: message.content + delta
                              };
                      } else {
                        return message;
                      }
                    });
        });
  };
  var streamCompletion = async function (history) {
    var controller = new AbortController();
    abortRef.current = Caml_option.some(controller);
    setStatus(function (param) {
          return "Streaming";
        });
    setError(function (param) {
          
        });
    var payload = {
      messages: history.filter(function (message) {
              return !(message.role === "assistant" && message.content === "");
            }).map(Message.toApi)
    };
    try {
      var response = await fetch("/api/chat", {
            method: "POST",
            headers: Object.fromEntries([[
                    "Content-Type",
                    "application/json"
                  ]]),
            body: Core__Option.getOr(JSON.stringify(payload), "{}"),
            signal: Caml_option.some(controller.signal)
          });
      if (response.ok) {
        var stream = response.body;
        if (stream == null) {
          setError(function (param) {
                return "The chat API returned an empty body";
              });
        } else {
          await Sse.consume(stream, appendDelta);
        }
      } else {
        var body;
        try {
          body = await response.json();
        }
        catch (exn){
          body = await response.text();
        }
        setError(function (param) {
              return Core__Option.getOr(Message.errorMessage(body), "Request failed");
            });
      }
    }
    catch (raw_exn){
      var exn$1 = Caml_js_exceptions.internalToOCamlException(raw_exn);
      var err = Caml_js_exceptions.as_js_exn(exn$1);
      if (err !== undefined) {
        var err$1 = Caml_option.valFromOption(err);
        if (WebApi.isAbortError(err$1)) {
          
        } else {
          setError(function (param) {
                return Core__Option.getOr(err$1.message, "Request failed");
              });
        }
      } else {
        setError(function (param) {
              return "Request failed";
            });
      }
    }
    abortRef.current = undefined;
    return setStatus(function (param) {
                return "Idle";
              });
  };
  var submit = function (text) {
    var trimmed = text.trim();
    if (trimmed === "" || streaming) {
      return ;
    }
    var user_id = nextId();
    var user = {
      id: user_id,
      role: "user",
      content: trimmed
    };
    var assistant_id = nextId();
    var assistant = {
      id: assistant_id,
      role: "assistant",
      content: ""
    };
    var nextMessages = messages.concat([
          user,
          assistant
        ]);
    setMessages(function (param) {
          return nextMessages;
        });
    setInput(function (param) {
          return "";
        });
    streamCompletion(nextMessages);
  };
  var onSubmit = function ($$event) {
    $$event.preventDefault();
    submit(input);
  };
  var onKeyDown = function ($$event) {
    if ($$event.key === "Enter" && !$$event.shiftKey) {
      $$event.preventDefault();
      return submit(input);
    }
    
  };
  var modelLabel = config !== undefined ? (
      config.demo ? "demo" : config.model
    ) : "…";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("header", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("span", {
                                            children: "Chat",
                                            className: "font-semibold tracking-tight"
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: "/",
                                            className: "text-foreground/25"
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: "ReScript",
                                            className: "text-sm text-[#e6484f] font-medium truncate"
                                          })
                                    ],
                                    className: "flex items-center gap-2 min-w-0"
                                  }),
                              JsxRuntime.jsx("div", {
                                    children: modelLabel + " · OpenAI-compatible",
                                    className: "text-xs font-mono text-foreground/45 truncate"
                                  })
                            ],
                            className: "max-w-2xl mx-auto px-4 h-14 flex items-center justify-between gap-4"
                          }),
                      className: "sticky top-0 z-10 border-b border-black/[.08] dark:border-white/[.08] bg-background/80 backdrop-blur"
                    }),
                JsxRuntime.jsx("main", {
                      children: JsxRuntime.jsx("div", {
                            children: messages.length !== 0 ? JsxRuntime.jsxs("div", {
                                    children: [
                                      messages.map(function (message) {
                                            var isUser = message.role === "user";
                                            var showCursor = streaming && !isUser && Core__Option.getOr(Core__Option.map(messages[messages.length - 1 | 0], (function (last) {
                                                        return last.id === message.id;
                                                      })), false);
                                            return JsxRuntime.jsx("div", {
                                                        children: JsxRuntime.jsx("div", {
                                                              children: message.content === "" && showCursor ? JsxRuntime.jsx("span", {
                                                                      className: "inline-block w-1.5 h-4 align-middle bg-foreground/50 animate-pulse"
                                                                    }) : JsxRuntime.jsxs(JsxRuntime.Fragment, {
                                                                      children: [
                                                                        message.content,
                                                                        showCursor ? JsxRuntime.jsx("span", {
                                                                                className: "inline-block w-[2px] h-4 ml-0.5 align-middle bg-foreground/70 animate-pulse"
                                                                              }) : null
                                                                      ]
                                                                    }),
                                                              className: "max-w-[85%] text-sm leading-relaxed whitespace-pre-wrap break-words " + (
                                                                isUser ? "bg-foreground text-background rounded-2xl px-4 py-2.5" : "text-foreground/90"
                                                              )
                                                            }),
                                                        className: "flex " + (
                                                          isUser ? "justify-end" : "justify-start"
                                                        )
                                                      }, message.id);
                                          }),
                                      JsxRuntime.jsx("div", {
                                            ref: Caml_option.some(bottomRef)
                                          })
                                    ],
                                    className: "flex flex-col gap-5"
                                  }) : JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("h1", {
                                                    children: "Talk to any OpenAI-compatible model",
                                                    className: "text-2xl font-semibold tracking-tight"
                                                  }),
                                              JsxRuntime.jsx("p", {
                                                    children: "This template streams Chat Completions from /api/chat. Point OPENAI_BASE_URL at OpenAI, OpenRouter, Groq, Ollama, or any compatible server.",
                                                    className: "text-sm text-foreground/50 max-w-md"
                                                  })
                                            ],
                                            className: "flex flex-col gap-2"
                                          }),
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("p", {
                                                    children: "Try",
                                                    className: "text-xs font-mono text-foreground/40"
                                                  }),
                                              JsxRuntime.jsx("div", {
                                                    children: prompts.map(function (prompt) {
                                                          return JsxRuntime.jsx("button", {
                                                                      children: prompt,
                                                                      className: "text-left text-sm px-4 py-3 rounded-lg border border-black/[.08] dark:border-white/[.12] hover:bg-black/[.03] dark:hover:bg-white/[.04] transition-colors",
                                                                      type: "button",
                                                                      onClick: (function (param) {
                                                                          submit(prompt);
                                                                        })
                                                                    }, prompt);
                                                        }),
                                                    className: "flex flex-col gap-2"
                                                  })
                                            ],
                                            className: "flex flex-col gap-2"
                                          })
                                    ],
                                    className: "flex flex-col gap-8 pt-10"
                                  }),
                            className: "max-w-2xl mx-auto px-4 py-8 flex flex-col gap-6"
                          }),
                      className: "flex-1 overflow-y-auto"
                    }),
                JsxRuntime.jsx("footer", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              config !== undefined && config.demo ? JsxRuntime.jsx("p", {
                                      children: "Demo mode — add OPENAI_API_KEY in .env.local to use a real model.",
                                      className: "text-xs text-foreground/45"
                                    }) : null,
                              error !== undefined ? JsxRuntime.jsx("p", {
                                      children: error,
                                      className: "text-xs text-red-600 dark:text-red-400"
                                    }) : null,
                              JsxRuntime.jsxs("form", {
                                    children: [
                                      JsxRuntime.jsx("textarea", {
                                            className: "flex-1 resize-none min-h-11 max-h-40 px-4 py-2.5 text-sm rounded-2xl border border-black/[.08] dark:border-white/[.12] bg-black/[.02] dark:bg-white/[.03] outline-none focus:border-foreground/30",
                                            autoFocus: true,
                                            placeholder: "Message",
                                            rows: 1,
                                            value: input,
                                            onKeyDown: onKeyDown,
                                            onChange: (function ($$event) {
                                                var target = $$event.target;
                                                setInput(function (param) {
                                                      return target.value;
                                                    });
                                              })
                                          }),
                                      streaming ? JsxRuntime.jsx("button", {
                                              children: "Stop",
                                              className: "h-11 px-4 rounded-2xl bg-foreground text-background text-sm font-medium hover:opacity-90",
                                              type: "button",
                                              onClick: (function (param) {
                                                  stop();
                                                })
                                            }) : JsxRuntime.jsx("button", {
                                              children: "Send",
                                              className: "h-11 px-4 rounded-2xl bg-foreground text-background text-sm font-medium hover:opacity-90 disabled:opacity-30",
                                              disabled: input.trim() === "",
                                              type: "submit"
                                            })
                                    ],
                                    className: "flex items-end gap-2",
                                    onSubmit: onSubmit
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: "Next.js 16 + ReScript 11 + Bun · POST /api/chat",
                                    className: "text-[11px] text-foreground/30 font-mono"
                                  })
                            ],
                            className: "max-w-2xl mx-auto px-4 py-4 flex flex-col gap-3"
                          }),
                      className: "sticky bottom-0 bg-background/80 backdrop-blur border-t border-black/[.08] dark:border-white/[.08]"
                    })
              ],
              className: "font-sans min-h-screen flex flex-col"
            });
}

var make = Chat;

var $$default = Chat;

export {
  prompts ,
  make ,
  $$default as default,
}
/* react Not a pure module */
