'use client'
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function CodeBlock(props) {
  var examples = props.examples;
  var match = React.useState(function () {
        return 0;
      });
  var setActiveExample = match[1];
  var activeExample = match[0];
  var match$1 = React.useState(function () {
        return "res";
      });
  var setActiveTab = match$1[1];
  var activeTab = match$1[0];
  var current = Core__Option.getOr(examples[activeExample], examples[0]);
  return JsxRuntime.jsxs("div", {
              children: [
                examples.length > 1 ? JsxRuntime.jsx("div", {
                        children: examples.map(function (example, i) {
                              var isActive = i === activeExample;
                              return JsxRuntime.jsx("button", {
                                          children: example.label,
                                          className: "px-3 py-1 text-xs rounded-full transition-colors " + (
                                            isActive ? "bg-foreground text-background" : "text-foreground/50 hover:text-foreground/80"
                                          ),
                                          onClick: (function (param) {
                                              setActiveExample(function (param) {
                                                    return i;
                                                  });
                                              setActiveTab(function (param) {
                                                    return "res";
                                                  });
                                            })
                                        }, i.toString());
                            }),
                        className: "flex gap-1 mb-3"
                      }) : null,
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: ".res",
                                      className: "px-4 py-2 text-xs font-mono transition-colors border-b-2 " + (
                                        activeTab === "res" ? "border-foreground/80 text-foreground" : "border-transparent text-foreground/40 hover:text-foreground/60"
                                      ),
                                      onClick: (function (param) {
                                          setActiveTab(function (param) {
                                                return "res";
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: ".res.mjs",
                                      className: "px-4 py-2 text-xs font-mono transition-colors border-b-2 " + (
                                        activeTab === "mjs" ? "border-foreground/80 text-foreground" : "border-transparent text-foreground/40 hover:text-foreground/60"
                                      ),
                                      onClick: (function (param) {
                                          setActiveTab(function (param) {
                                                return "mjs";
                                              });
                                        })
                                    })
                              ],
                              className: "flex items-center gap-0 bg-black/[.03] dark:bg-white/[.03] border-b border-black/[.08] dark:border-white/[.08]"
                            }),
                        JsxRuntime.jsx("pre", {
                              children: JsxRuntime.jsx("code", {
                                    children: activeTab === "res" ? current.resCode : current.jsCode,
                                    className: "font-mono text-foreground/80"
                                  }),
                              className: "p-4 overflow-x-auto text-[13px] leading-relaxed bg-black/[.02] dark:bg-white/[.02]"
                            })
                      ],
                      className: "rounded-lg border border-black/[.08] dark:border-white/[.12] overflow-hidden"
                    })
              ],
              className: "w-full max-w-2xl"
            });
}

var make = CodeBlock;

var $$default = CodeBlock;

export {
  make ,
  $$default as default,
}
/* react Not a pure module */
