// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMonoFont = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});
;

import "./globals.css"
;

function Layout(props) {
  return JsxRuntime.jsx("html", {
              children: JsxRuntime.jsx("body", {
                    children: props.children,
                    className: geistSans.variable + " " + geistMonoFont.variable + " antialiased"
                  }),
              lang: "en"
            });
}

var metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: undefined,
  authors: undefined,
  creator: undefined,
  publisher: undefined,
  robots: undefined,
  openGraph: undefined,
  twitter: undefined,
  viewport: undefined,
  themeColor: undefined,
  colorScheme: undefined,
  manifest: undefined,
  icons: undefined
};

var make = Layout;

var $$default = Layout;

export {
  metadata ,
  make ,
  $$default as default,
}
/*  Not a pure module */
