// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CodeBlock from "./CodeBlock.res.mjs";
import $$Image from "next/image";
import * as JsxRuntime from "react/jsx-runtime";

var $$Image$1 = {};

var componentExample = {
  label: "Component",
  resCode: "@react.component\nlet make = () => {\n  let (count, setCount) = React.useState(() => 0)\n\n  <button onClick={_ => setCount(c => c + 1)}>\n    {React.string(\"Clicks: \" ++ Int.toString(count))}\n  </button>\n}",
  jsCode: "import { jsx } from \"react/jsx-runtime\";\nimport { useState } from \"react\";\n\nfunction make() {\n  let [count, setCount] = useState(() => 0);\n\n  return jsx(\"button\", {\n    onClick: () => setCount(c => c + 1),\n    children: \"Clicks: \" + count.toString()\n  });\n}"
};

var bindingExample = {
  label: "Binding",
  resCode: "// Type-safe bindings to Next.js APIs\nmodule Link = {\n  @module(\"next/link\") @react.component\n  external make: (\n    ~href: string,\n    ~prefetch: bool=?,\n    ~className: string=?,\n    ~children: React.element,\n  ) => React.element = \"default\"\n}\n\n// Used like any ReScript component\n<Link href=\"/about\" prefetch={true}>\n  {React.string(\"About\")}\n</Link>",
  jsCode: "// Compiles to a direct import — zero overhead\nimport Link from \"next/link\";\n\njsx(Link, {\n  href: \"/about\",\n  prefetch: true,\n  children: \"About\"\n});"
};

var serverExample = {
  label: "Server",
  resCode: "// Async server APIs (Next.js 16)\nmodule Cookies = {\n  type cookieStore\n  type cookieValue = { name: string, value: string }\n\n  @module(\"next/headers\")\n  external cookies: unit => promise<cookieStore>\n    = \"cookies\"\n\n  @send\n  external get: (cookieStore, string)\n    => option<cookieValue> = \"get\"\n}\n\n// Usage in a server component\nlet token = await Cookies.cookies()\n  ->Cookies.get(\"session\")",
  jsCode: "import { cookies } from \"next/headers\";\n\n// Direct call — ReScript externals compile away\nlet token = (await cookies()).get(\"session\");"
};

function Page(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("main", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx($$Image, {
                                              className: "dark:invert",
                                              src: "/next.svg",
                                              alt: "Next.js logo",
                                              width: 120,
                                              height: 25,
                                              priority: true
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "+",
                                              className: "text-2xl font-light text-foreground/20"
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: "ReScript",
                                              className: "text-xl font-bold tracking-tight text-[#e6484f]"
                                            })
                                      ],
                                      className: "flex items-center gap-3"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Write Next.js apps in ReScript. The compiler catches your mistakes, the output is clean JS.",
                                      className: "text-sm text-foreground/50"
                                    })
                              ],
                              className: "flex flex-col gap-3"
                            }),
                        JsxRuntime.jsx(CodeBlock.make, {
                              examples: [
                                componentExample,
                                bindingExample,
                                serverExample
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("p", {
                                      children: "Get started",
                                      className: "text-xs font-mono text-foreground/40"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "bun create next-rescript-app my-app",
                                      className: "font-mono text-sm bg-black/[.03] dark:bg-white/[.03] border border-black/[.08] dark:border-white/[.08] rounded-lg px-4 py-3 text-foreground/70 select-all"
                                    }),
                                JsxRuntime.jsxs("p", {
                                      children: [
                                        "or edit ",
                                        JsxRuntime.jsx("code", {
                                              children: "src/app/page.res",
                                              className: "bg-black/[.05] dark:bg-white/[.06] font-mono font-medium px-1 py-0.5 rounded text-foreground/60"
                                            }),
                                        " to start building."
                                      ],
                                      className: "text-xs text-foreground/40 mt-1"
                                    })
                              ],
                              className: "flex flex-col gap-2 w-full"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("a", {
                                      children: "ReScript Docs",
                                      className: "rounded-full border border-solid border-transparent bg-foreground text-background hover:bg-[#383838] dark:hover:bg-[#ccc] font-medium text-sm h-9 px-4 flex items-center transition-colors",
                                      href: "https://rescript-lang.org/docs/manual/latest/introduction",
                                      rel: "noopener noreferrer",
                                      target: "_blank"
                                    }),
                                JsxRuntime.jsx("a", {
                                      children: "Next.js Docs",
                                      className: "rounded-full border border-solid border-black/[.08] dark:border-white/[.145] hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent font-medium text-sm h-9 px-4 flex items-center transition-colors",
                                      href: "https://nextjs.org/docs",
                                      rel: "noopener noreferrer",
                                      target: "_blank"
                                    }),
                                JsxRuntime.jsx("a", {
                                      children: "GitHub",
                                      className: "rounded-full border border-solid border-black/[.08] dark:border-white/[.145] hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent font-medium text-sm h-9 px-4 flex items-center transition-colors",
                                      href: "https://github.com/acald-creator/next-rescript-app-router-bun",
                                      rel: "noopener noreferrer",
                                      target: "_blank"
                                    })
                              ],
                              className: "flex gap-3 flex-wrap"
                            })
                      ],
                      className: "flex flex-col gap-10 items-center sm:items-start max-w-2xl w-full"
                    }),
                JsxRuntime.jsx("footer", {
                      children: "Next.js 16 + ReScript 11 + Bun",
                      className: "text-xs text-foreground/30 font-mono"
                    })
              ],
              className: "font-sans grid grid-rows-[1fr_auto] items-center justify-items-center min-h-screen p-8 pb-12 gap-16 sm:p-20"
            });
}

var make = Page;

var $$default = Page;

export {
  $$Image$1 as $$Image,
  componentExample ,
  bindingExample ,
  serverExample ,
  make ,
  $$default as default,
}
/* CodeBlock Not a pure module */
