// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Chat from "./Chat.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Page(props) {
  return JsxRuntime.jsx(Chat.make, {});
}

var make = Page;

var $$default = Page;

export {
  make ,
  $$default as default,
}
/* Chat Not a pure module */
