// Generated by ReScript, PLEASE EDIT WITH CARE

import $$Image from "next/image";
import * as JsxRuntime from "react/jsx-runtime";

var $$Image$1 = {};

function Page(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("main", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx($$Image, {
                                      className: "dark:invert",
                                      src: "/next.svg",
                                      alt: "Next.js logo",
                                      width: 180,
                                      height: 38,
                                      priority: true
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: "+",
                                      className: "text-4xl font-light text-foreground/30"
                                    }),
                                JsxRuntime.jsx("span", {
                                      children: "ReScript",
                                      className: "text-3xl font-bold tracking-tight text-[#e6484f]"
                                    })
                              ],
                              className: "flex items-center gap-4"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "A Next.js 15 App Router application written in ReScript. Type-safe, functional, and fast.",
                              className: "text-center sm:text-left text-sm text-foreground/60 max-w-md"
                            }),
                        JsxRuntime.jsxs("ol", {
                              children: [
                                JsxRuntime.jsxs("li", {
                                      children: [
                                        "Get started by editing ",
                                        JsxRuntime.jsx("code", {
                                              children: "src/app/page.res",
                                              className: "bg-black/[.05] dark:bg-white/[.06] font-mono font-semibold px-1 py-0.5 rounded"
                                            }),
                                        "."
                                      ],
                                      className: "mb-2 tracking-[-.01em]"
                                    }),
                                JsxRuntime.jsx("li", {
                                      children: "Save and see your changes instantly.",
                                      className: "tracking-[-.01em]"
                                    })
                              ],
                              className: "font-mono list-inside list-decimal text-sm/6 text-center sm:text-left"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("a", {
                                      children: "ReScript Docs",
                                      className: "rounded-full border border-solid border-transparent transition-colors flex items-center justify-center bg-foreground text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#ccc] font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 sm:w-auto",
                                      href: "https://rescript-lang.org/docs/manual/latest/introduction",
                                      rel: "noopener noreferrer",
                                      target: "_blank"
                                    }),
                                JsxRuntime.jsx("a", {
                                      children: "Next.js Docs",
                                      className: "rounded-full border border-solid border-black/[.08] dark:border-white/[.145] transition-colors flex items-center justify-center hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 w-full sm:w-auto md:w-[158px]",
                                      href: "https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app",
                                      rel: "noopener noreferrer",
                                      target: "_blank"
                                    })
                              ],
                              className: "flex gap-4 items-center flex-col sm:flex-row"
                            })
                      ],
                      className: "flex flex-col gap-[32px] row-start-2 items-center sm:items-start"
                    }),
                JsxRuntime.jsxs("footer", {
                      children: [
                        JsxRuntime.jsxs("a", {
                              children: [
                                JsxRuntime.jsx($$Image, {
                                      src: "/file.svg",
                                      alt: "File icon",
                                      width: 16,
                                      height: 16
                                    }),
                                "ReScript"
                              ],
                              className: "flex items-center gap-2 hover:underline hover:underline-offset-4",
                              href: "https://rescript-lang.org",
                              rel: "noopener noreferrer",
                              target: "_blank"
                            }),
                        JsxRuntime.jsxs("a", {
                              children: [
                                JsxRuntime.jsx($$Image, {
                                      src: "/window.svg",
                                      alt: "Window icon",
                                      width: 16,
                                      height: 16
                                    }),
                                "Learn Next.js"
                              ],
                              className: "flex items-center gap-2 hover:underline hover:underline-offset-4",
                              href: "https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app",
                              rel: "noopener noreferrer",
                              target: "_blank"
                            }),
                        JsxRuntime.jsxs("a", {
                              children: [
                                JsxRuntime.jsx($$Image, {
                                      src: "/globe.svg",
                                      alt: "Globe icon",
                                      width: 16,
                                      height: 16
                                    }),
                                "GitHub"
                              ],
                              className: "flex items-center gap-2 hover:underline hover:underline-offset-4",
                              href: "https://github.com/rescript-lang/rescript",
                              rel: "noopener noreferrer",
                              target: "_blank"
                            })
                      ],
                      className: "row-start-3 flex gap-[24px] flex-wrap items-center justify-center"
                    })
              ],
              className: "font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20"
            });
}

var make = Page;

var $$default = Page;

export {
  $$Image$1 as $$Image,
  make ,
  $$default as default,
}
/* next/image Not a pure module */
