// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OpenAI from "../../../chat/OpenAI.res.mjs";
import * as Message from "../../../chat/Message.res.mjs";

function errorResponse(message, status) {
  return Response.json({
              error: message
            }, {
              status: status
            });
}

async function GET(_request) {
  return Response.json(OpenAI.publicConfig(), {
              status: 200
            });
}

async function POST(request) {
  var json;
  try {
    json = await request.json();
  }
  catch (exn){
    json = Object.fromEntries([]);
  }
  var message = Message.decodeRequest(json);
  if (message.TAG !== "Ok") {
    return errorResponse(message._0, 400);
  }
  var err = await OpenAI.complete(message._0);
  if (err.TAG === "Ok") {
    return new Response(err._0, {
                status: 200,
                headers: OpenAI.streamHeaders
              });
  }
  var err$1 = err._0;
  return errorResponse(err$1.message, err$1.status);
}

var dynamic = "force-dynamic";

var maxDuration = 60;

export {
  dynamic ,
  maxDuration ,
  errorResponse ,
  GET ,
  POST ,
}
/* OpenAI Not a pure module */
